image: node:11

stages:
  - prepare
  - code
  - build
  - deploy

cache:
  paths:
    - node_modules/
    - generated/

Prepare:
  stage: prepare
  before_script:
    - apt-get update && apt install libsecret-1-dev -y
  script:
    - npm i
  artifacts:
    paths:
      - node_modules/
  only:
    - integration
    - goerli
    - master

Codegen-Kovan:
  stage: code
  script:
    - npm run codegen:kovan
  artifacts:
    paths:
      - generated/
  only:
    - integration
Codegen-Goerli:
  stage: code
  script:
    - npm run codegen:goerli
  artifacts:
    paths:
      - generated/
  only:
    - goerli
Codegen-Mainnet:
  stage: code
  script:
    - npm run codegen:mainnet
  artifacts:
    paths:
      - generated/
  only:
    - master

Build-Kovan:
  stage: build
  script:
    - npm run build:kovan
  artifacts:
    paths:
      - generated/
  only:
    - integration
Build-Goerli:
  stage: build
  script:
    - npm run build:goerli
  artifacts:
    paths:
      - generated/
  only:
    - goerli
Build-Mainnet:
  stage: build
  script:
    - npm run build:mainnet
  artifacts:
    paths:
      - generated/
  only:
    - master

Deploy-Kovan:
  stage: deploy
  before_script:
    - apt-get update && apt install libsecret-1-dev -y
  script:
    - npm run deploy:kovan
  only:
    - integration
Deploy-Goerli:
  stage: deploy
  before_script:
    - apt-get update && apt install libsecret-1-dev -y
  script:
    - npm run deploy:goerli
  only:
    - goerli
Deploy-Mainnet:
  stage: deploy
  before_script:
    - apt-get update && apt install libsecret-1-dev -y
  script:
    - npm run deploy:mainnet
  only:
    - master
